spring.application.name=Backend_Epilogo

# Configuración de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/ProyectoDB
spring.datasource.username=postgres
spring.datasource.password=Salito
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=8080

# Usuario de prueba para endpoint (SPRING SECURITY )
spring.security.user.name=admin
spring.security.user.password=admin

# Seguridad - Tiempo de expiración del token JWT (24 horas)
jwt.secret=claveSuperSecretaParaGenerarTokensJWTEnNuestraAplicacionDeReservaDeLibros
jwt.expiration=86400000

# Internacionalización
spring.messages.basename=i18n/messages
spring.web.locale=es
spring.web.locale-resolver=fixed

